[versions]
# 插件版本
agp = "8.7.3"
kotlin = "2.1.10"

# 库版本
xposed-api = "master-SNAPSHOT"
libsu = "6.0.0"
androidx-core = "1.12.0"
appcompat = "1.6.1"
material = "1.9.0"
constraintlayout = "2.1.4"

[libraries]
# LibXposed API 核心 (直接从 JitPack 引用 api 仓库)
libxposed-api = { group = "com.github.libxposed", name = "api", version.ref = "xposed-api" }

# Libsu
libsu-core = { group = "com.github.topjohnwu", name = "libsu", version.ref = "libsu" }

# AndroidX & UI
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
